Scientific Python
=================


:::{admonition} Learning Objectives
- describe numpy and pandas packages
- create numpy ndarrays
- create dataframe from csv file
- inspect structure of dataframe
- handle missing values in dataframe
- index dataframe based on label (loc), integer index (iloc), logical conditions, and [] operator
- concatenate and merge dataframes
- drop columns and rows from dataframes
- change datatypes of columns
- apply function to column and add as new column to dataframe
:::


## Recap

## Packages

When packages are installed, they can be loaded into the python session with
the `import` command. To avoid having to type the full name of the module
we define an alias using the `as` keyword. By convention, the alias for
`numpy` is `np` and the alias for `pandas` is `pd`. 

Lets start by loading in numpy and pandas:

In [1]:
import numpy as np
import pandas as pd

## Numpy

**NumPy** (Numerical Python) is a package that provides functions and 
data structures for working with numerical data. NumPy functions are generally 
more intuitive, and more computationally efficient for working with lots 
of numbers than Python's built-in options. It has become the standard for 
working with numeric data in python.

## Numpy Arrays

NumPy provides an **array** object. Arrays are a critical data structure for
working with numerical data and some version of array can be found in pretty
much every commonly used programming language. NumPy's array is different from 
the python list object in that each element needs to be the same data type, 
and its size is set on its creation.

If you are working in python for data analysis, data science, 
machine learning, etc. you will run into numpy arrays. 

There are several ways to create an ndarray. In this case we will use a 
list (built-in python object) of numbers as the input for our array creation:

In [2]:
arr = np.array([1, 3, 9, 2])
arr

array([1, 3, 9, 2])

We can see the number of elements in the array with the `shape` attribute:

In [3]:
arr.shape

(4,)

The `shape` attribute reflects the number of elements in each **dimension** of
the ndarray. In this case, there are four elements and only one dimension.

**Dimensions** refers to the number of **axes** that represents the data. For 
example if you are working with lat/long coordinates you will probably
have 2 dimensions in your data. If working with images you may have 3 
dimensions: x,y and color.

To see the number of of dimensions of the array object use `ndim`:

In [4]:
arr.ndim

1

As mentioned earlier, unlike python's built-in list type, each element
in an ndarray are the same data type. Recall that we created this array,
we did not specify a data type for numpy to use. As a result, numpy inferred
a data type from values in the list. We can access the datatype from
the `dtype` attribute of the array:

In [5]:
arr.dtype 

dtype('int64')

To explicitly define the datatype you want for the array you create, pass
the dtype parameter when creating the array:

In [6]:
arr = np.array([1, 3, 9, 2], dtype=np.int8)
arr 

array([1, 3, 9, 2], dtype=int8)

```{Note}
For reference here is a list of common datatypes in data analysis:
- bool
- int
- float
- datetime
- string
- object
```

## Indexing Numpy Arrays

To access an element from the array use the `[]` operator:

In [7]:
display(arr)
arr[3]

array([1, 3, 9, 2], dtype=int8)

2

We can access more than one element with python slicing:

In [8]:
display(arr)
arr[1:3:1]

array([1, 3, 9, 2], dtype=int8)

array([3, 9], dtype=int8)

We can use integer arrays as indexes:

In [9]:
display(arr)
arr[[1,2,0]]

array([1, 3, 9, 2], dtype=int8)

array([3, 9, 1], dtype=int8)

We can also use boolean arrays as indexes:

In [10]:
display(arr)
arr[[True,False,True,True]]

array([1, 3, 9, 2], dtype=int8)

array([1, 9, 2], dtype=int8)

We can use indexing to modify the selected elements:

In [11]:
display(arr)
arr[3] = 78
arr[[1,2]] = [0,9]
arr

array([1, 3, 9, 2], dtype=int8)

array([ 1,  0,  9, 78], dtype=int8)

Notice what happens when we pass a value that is not an integer:

In [12]:
display(arr)
arr[3] = 7.8
arr

array([ 1,  0,  9, 78], dtype=int8)

array([1, 0, 9, 7], dtype=int8)

NumPy has converted 7.8 to an integer before entering it into the array. This
will only work if there is an accepted way of converting to integer, for 
example it will fail if something like this is passed:

In [13]:
try:
    arr[3] = "hello"
except ValueError as e:
    print(e)

invalid literal for int() with base 10: 'hello'


## Operating on NumPy Arrays

In general, operations are applied element by element on the array:

In [14]:
display(arr)
arr * 2

array([1, 0, 9, 7], dtype=int8)

array([ 2,  0, 18, 14], dtype=int8)

Another example but with comparison operators:

In [15]:
display(arr)
arr > 3

array([1, 0, 9, 7], dtype=int8)

array([False, False,  True,  True])

This fits in nicely with indexing using boolean array from before:

In [16]:
display(arr)
arr[arr>3]

array([1, 0, 9, 7], dtype=int8)

array([9, 7], dtype=int8)

## Multi Dimensional Arrays + Other Ways to Create Arrays

Now let us see some of these concepts with a 2-D array. As before, we can
define a 2-D array by passing a python list as input:

In [17]:
arr = np.array([[1,2], [3,4]], dtype=np.int8)

Here is another way of initializing an array:

In [18]:
arr = np.zeros((3,4), dtype=np.float64)
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Pandas

**Pandas** is a package that provides the **data frame** object. As well as
many functions for working with data, including functions for:
- loading and writing data to/from files and databases
- summarizing data
- handling missing data
- reshaping and transforming data
- subsetting and filtering data
- merging and combining datasets


## Load in data

First, we will load in a dataset from a csv using the `read_csv()` function 
from pandas: 

```{tip} 
You can look at the documentation for this function either online, 
from the python shell using: `help(pd.read_csv)`, or using the ? operator 
in Ipython (or notebook)
```

In [19]:
dataset = pd.read_csv() # should the input be a url?

TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'

We can use the `head()` method to see what we have.

In [ ]:
dataset.head()

Here we see a dataframe, which is the really important part of pandas, which we
will spend lots of time with during this lesson and the next. 
The dataframe is the tool we can merge, join, summarize, etc.

## Dataframes

A **dataframe** is how pandas structures tabular data - data structured as rows
and columns. In general rows are observations, and columns are variables.
Each entry is called a cell.


## Methods for Exploring Dataframes

As with the `head()` method there are many other methods for looking 
at the contents of a pandas dataframe.

`head()` shows the first rows of the dataframe, to see the last rows, use
`tail()`. By default, the the number of rows displayed is 5, this amount
can be modified by passing an optional integer argument to the function call.
Both `head()` and `tail()` accept this optional integer argument.

In [ ]:
dataset.tail(10)

To display the columns of the dataframe we can access the columns attribute
of the dataframe object.

In [ ]:
dataset.columns

In [ ]:
dataset.info

In [ ]:
dataset.describe()

## Missing Values

## Data Types

In [ ]:
dataset.dtypes

## Indexing

In [ ]:
dataset.loc # label based or boolean array
dataset.iloc # interger based
dataset[colname]
dataset[[colnames]]
dataset[colname][4]

## Modiying DataFrames
dropping values
dropping columns
Concat 
Join
cleaning
changing datatypes